- hosts: localhost
  become: true

  tasks:
    - include: tasks/users.yml
    - include: tasks/packages.yml
    - include: tasks/cron.yml
    - include: tasks/deploy-anaconda.yml
    - include: tasks/anaconda-packages.yml
    - include: tasks/ngspice.yml
    - include: tasks/gui.yml

