- name: Check for Cadence installation
  stat: path=/opt/cadence/bin
  changed_when: false
  register: cadence_folder

- block:
  - name: Extract ICADV12.30.700
    shell: |
      mkdir -p /tmp/ICADV12.30.700
      tar xf /shared/karan/S3sync/ICADV12.30.700.tar.gz -C /tmp/ICADV12.30.700
  - name: Extract ISCAPE
    shell: |
      mkdir -p /tmp/iscape
      tar xf /tmp/ICADV12.30.700/ICADV12.30.700/IScape04.23-s012lnx86.t.Z -C /tmp/iscape
  - name: Install Cadence
    shell: |
      mkdir -p /opt/cadence
      /tmp/iscape/iscape/bin/iscape.sh -batch majorAction=InstallFromArchive archiveDirectory=/tmp/ICADV12.30.700/ICADV12.30.700/ installDirectory=/opt/cadence
  - name: Cleaning Cadence Install
    shell: |
      rm -rf /tmp/ICADV12.30.700 /tmp/iscape
  args:
    warn: false
  when: not cadence_folder.stat.exists
