
- name: Install EPEL
  yum: name={{item}}
  with_items:
    - epel-release

- name: Install packages
  yum: pkg={{item}} state=installed
  with_items:
    - '@Development tools'
    - '@^GNOME Desktop'
    - bzip2
    - glibc.i686
    - glibc-devel.i686
    - glibc-devel
    - htop
    - libGLU
    - libXaw-devel
    - lua
    - lua-devel
    - lua-filesystem
    - lua-posix
    - ksh
    - open-vm-tools
    - tcl
    - tcl-devel
    - vim
    - wget
