
- name: Check for Miniconda installation
  stat: path=/opt/anaconda/bin/conda
  changed_when: false
  register: conda_binary

- name: Install Anaconda
  when: not conda_binary.stat.exists
  shell: | 
      curl -s -o miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
      bash miniconda.sh -b -f -p /opt/anaconda
      rm -f miniconda.sh

