
- name: Install EPEL
  yum: name={{item}}
  with_items:
    - epel-release

- name: Upgrade packages
  yum:
    name: '*'
    state: latest

- name: Install packages
  yum: 
    name: "@Development tools" "@^GNOME Desktop" bzip2 htop wget vim

