
- name: Install EPEL
  yum: name={{item}}
  with_items:
    - epel-release

- name: Upgrade packages
  yum:
    name: '*'
    state: latest

- name: Install packages
  yum: pkg={{item}} state=installed
  with_items:
    - '@Development tools'
    - '@^GNOME Desktop'
    - bzip2
    - htop 
    - libXaw-devel
    - vim
    - wget
    - 

