## Cadence Install Scape
- name: Check for Install Scape installation
  stat: path=/shared/software/cadence/iscape
  changed_when: false
  register: cadence_iscape_folder

- name: Extract ISCAPE
  when: not cadence_iscape_folder.stat.exists
  shell: |
    set -e
    mkdir -p /tmp/ICADV12.30.700
    tar xf /shared/karan/S3sync/ICADV12.30.700.tar.gz -C /tmp/ICADV12.30.700
    mkdir -p /shared/software/cadence
    tar xf /tmp/ICADV12.30.700/ICADV12.30.700/IScape04.23-s012lnx86.t.Z -C /shared/software/cadence
    rm -rf /tmp/ICADV12.30.700

## Cadence Virtuoso
- name: Check for Cadence Virtuoso installation
  stat: path=/shared/software/cadence/ICADV123
  changed_when: false
  register: cadence_virtuoso_folder

- block:
  - name: Install ICADV Base Version
    shell: |
      set -e
      yum install -y sqlite-devel.i686 elfutils-libelf-devel.i686	
      mkdir -p /tmp/ICADV12.30.700
      tar xf /shared/karan/S3sync/ICADV12.30.700.tar.gz -C /tmp/ICADV12.30.700
      /shared/software/cadence/iscape/bin/iscape.sh -batch majorAction=InstallFromArchive archiveDirectory=/tmp/ICADV12.30.700/ICADV12.30.700/ installDirectory=/shared/software/cadence/ICADV123
      rm -rf /tmp/ICADV12.30.700
  - name: Install Hotfixes for ICADV12.30.823
    shell: |
      set -e
      mkdir -p /tmp/ICADV12.30.823
      tar xf /shared/software/Hotfix_ICADV12.30.823_lnx86_1of3.tar -C /tmp/ICADV12.30.823
      tar xf /shared/software/Hotfix_ICADV12.30.823_lnx86_2of3.tar -C /tmp/ICADV12.30.823  
      tar xf /shared/software/Hotfix_ICADV12.30.823_lnx86_3of3.tar -C /tmp/ICADV12.30.823
      mkdir -p /shared/software/cadence/ICADV123
      /shared/software/cadence/iscape/bin/iscape.sh -batch majorAction=InstallFromArchive archiveDirectory=/tmp/ICADV12.30.823/ICADV12.30.823_lnx86.Hotfix/CDROM1 installDirectory=/shared/software/cadence/ICADV123
      rm -rf /tmp/ICADV12.30.823
  when: not cadence_virtuoso_folder.stat.exists

## Cadence PVS

- name: Check for Cadence Physical Verification System installation
  stat: path=/shared/software/cadence/PVS161
  changed_when: false
  register: cadence_pvs_folder

- name: Install Cadence PVS
  when: not cadence_pvs_folder.stat.exists
  shell: |
    set -e
    yum install -y libXp
    mkdir -p /tmp/PVS16.13.s346
    tar xf /shared/karan/S3sync/PVS16.13.s346.tar.gz -C /tmp/PVS16.13.s346
    mkdir -p /shared/software/cadence/PVS161
    /shared/software/cadence/iscape/bin/iscape.sh -batch majorAction=InstallFromArchive archiveDirectory=/tmp/PVS16.13.s346/PVS16.13.s346/ installDirectory=/shared/software/cadence/PVS161
    rm -rf /tmp/PVS16.13.s346

## Cadence Spectre
- name: Check for Cadence Spectre installation
  stat: path=/shared/software/cadence/SPECTRE181
  changed_when: false
  register: cadence_spectre_folder

- name: Install Cadence Spectre
  when: not cadence_spectre_folder.stat.exists
  shell: |
    set -e
    mkdir -p /tmp/SPECTRE18.10.235
    tar xf /shared/karan/S3sync/SPECTRE18.10.235.tar.gz -C /tmp/SPECTRE18.10.235
    mkdir -p /shared/software/cadence/SPECTRE181
    /shared/software/cadence/iscape/bin/iscape.sh -batch majorAction=InstallFromArchive archiveDirectory=/tmp/SPECTRE18.10.235/SPECTRE18.10.235/ installDirectory=/shared/software/cadence/SPECTRE181
    rm -rf /tmp/SPECTRE18.10.235
