## Cadence Install Scape
- name: Check for Install Scape installation
  stat: path=/shared/software/cadence/iscape
  changed_when: false
  register: cadence_iscape_folder

- name: Extract ISCAPE
  when: not cadence_iscape_folder.stat.exists
  shell: |
    mkdir -p /tmp/ICADV12.30.700
    tar xf /shared/karan/S3sync/ICADV12.30.700.tar.gz -C /tmp/ICADV12.30.700
    mkdir -p /shared/software/cadence
    tar xf /tmp/ICADV12.30.700/ICADV12.30.700/IScape04.23-s012lnx86.t.Z -C /shared/software/cadence

## Cadence Virtuoso
- name: Check for Cadence Virtuoso installation
  stat: path=/shared/software/cadence/ICADV123
  changed_when: false
  register: cadence_virtuoso_folder

- name: Install ICADV12.30.700
  when: not cadence_virtuoso_folder.stat.exists
  shell: |
    yum install -y sqlite-devel.i686 elfutils-libelf-devel.i686
    mkdir -p /shared/software/cadence/ICADV123
    /shared/software/cadence/iscape/bin/iscape.sh -batch majorAction=InstallFromArchive archiveDirectory=/tmp/ICADV12.30.700/ICADV12.30.700/ installDirectory=/shared/software/cadence/ICADV123
    rm -rf /tmp/ICADV12.30.700

## Cadence PVS
- name: Check for Cadence Physical Verification System installation
  stat: path=/shared/software/cadence/PVS161
  changed_when: false
  register: cadence_pvs_folder

- name: Install Cadence PVS
  when: not cadence_pvs_folder.stat.exists
  shell: |
    yum install -y libXp
    mkdir -p /tmp/PVS16.13.s346
    tar xf /shared/karan/S3sync/PVS16.13.s346.tar.gz -C /tmp/PVS16.13.s346
    mkdir -p /shared/software/cadence/PVS161
    /shared/software/cadence/iscape/bin/iscape.sh -batch majorAction=InstallFromArchive archiveDirectory=/tmp/PVS16.13.s346/PVS16.13.s346/ installDirectory=/shared/software/cadence/PVS161
    rm -rf /tmp/PVS16.13.s346

## Cadence Spectre
- name: Check for Cadence Spectre installation
  stat: path=/shared/software/cadence/SPECTRE181
  changed_when: false
  register: cadence_spectre_folder

- name: Install Cadence Spectre
  when: not cadence_spectre_folder.stat.exists
  shell: |
    mkdir -p /tmp/SPECTRE18.10.235
    tar xf /shared/karan/S3sync/SPECTRE18.10.235.tar.gz -C /tmp/SPECTRE18.10.235
    mkdir -p /shared/software/cadence/SPECTRE181
    /shared/software/cadence/iscape/bin/iscape.sh -batch majorAction=InstallFromArchive archiveDirectory=/tmp/SPECTRE18.10.235/SPECTRE18.10.235/ installDirectory=/shared/software/cadence/SPECTRE181
    rm -rf /tmp/SPECTRE18.10.235

## Cadence Incisive Enterprise Simulator
- name: Check for Cadence Incisive Enterprise Simulator installation
  stat: path=/shared/software/cadence/INCISIVE152
  changed_when: false
  register: cadence_incisive_folder

- name: Install Cadence Incisive Enterprise Simulator
  when: not cadence_incisive_folder.stat.exists
  shell: |
    mkdir -p /tmp/INCISIVE15.20.056
    tar xf /shared/karan/S3sync/INCISIVE15.20.056.tar.gz -C /tmp/INCISIVE15.20.056
    mkdir -p /shared/software/cadence/INCISIVE152
    /shared/software/cadence/iscape/bin/iscape.sh -batch majorAction=InstallFromArchive archiveDirectory=/tmp/INCISIVE15.20.056/INCISIVE15.20.056/ installDirectory=/shared/software/cadence/INCISIVE152
    rm -rf /tmp/INCISIVE15.20.056

## Cadence Innovus
- name: Check for Cadence Innovus installation
  stat: path=/shared/software/cadence/INNOVUS171
  changed_when: false
  register: cadence_innovus_folder

- name: Install Cadence Innovus
  when: not cadence_innovus_folder.stat.exists
  shell: |
    mkdir -p /tmp/INCISIVE15.20.056
    tar xf /shared/karan/S3sync/INNOVUS17.15.000.tar.gz -C /tmp/INNOVUS17.15.000
    mkdir -p /shared/software/cadence/INNOVUS171
    /shared/software/cadence/iscape/bin/iscape.sh -batch majorAction=InstallFromArchive archiveDirectory=/tmp/INNOVUS17.15.000/INNOVUS17.15.000/ installDirectory=/shared/software/cadence/INNOVUS171
    rm -rf /tmp/INNOVUS17.15.000

## Cadence Conformal Equivalence Checker
- name: Check for Cadence Conformal Equivalence Checker installation
  stat: path=/shared/software/cadence/CONFRML171
  changed_when: false
  register: cadence_confrml_folder

- name: Install Cadence Conformal Equivalence Checker
  when: not cadence_confrml_folder.stat.exists
  shell: |
    mkdir -p /tmp/INCISIVE15.20.056
    tar xf /shared/karan/S3sync/CONFRML17.10.240.tar.gz -C /tmp/CONFRML17.10.240
    mkdir -p /shared/software/cadence/CONFRML171
    /shared/software/cadence/iscape/bin/iscape.sh -batch majorAction=InstallFromArchive archiveDirectory=/tmp/CONFRML17.10.240/CONFRML17.10.240/ installDirectory=/shared/software/cadence/CONFRML171
    rm -rf /tmp/CONFRML17.10.240
